const data = [
  {
    key: 0,
    product: "Maggi",
    price: "430",
    quantity: "43 Packets",
    thresholdValue: "12 Packets",
    date: "11/12/22",
    availability: "In- stock",
  },
  {
    key: 1,
    product: "Bru",
    price: "7257",
    quantity: "22 Packets",
    thresholdValue: "12 Packets",
    date: "21/12/22",
    availability: "Out of stock",
  },
  {
    key: 2,
    product: "Red Bull",
    price: "405",
    quantity: "36 Packets",
    thresholdValue: "9 Packets",
    date: "5/12/22",
    availability: "In- stock",
  },
  {
    key: 3,
    product: "Bourn Vita",
    price: "502",
    quantity: "14 Packets",
    thresholdValue: "6 Packets",
    date: "8/12/22",
    availability: "Out of stock",
  },
  {
    key: 4,
    product: "Horlicks",
    price: "530",
    quantity: "5 Packets",
    thresholdValue: "5 Packets",
    date: "9/1/23",
    availability: "In- stock",
  },
  {
    key: 5,
    product: "Harpic",
    price: "605",
    quantity: "10 Packets",
    thresholdValue: "5 Packets",
    date: "9/1/23",
    availability: "In- stock",
  },
  {
    key: 6,
    product: "Ariel",
    price: "408",
    quantity: "23 Packets",
    thresholdValue: "7 Packets",
    date: "15/12/23",
    availability: "Out of stock",
  },
  {
    key: 7,
    product: "Scotch Brite",
    price: "359",
    quantity: "43 Packets",
    thresholdValue: "8 Packets",
    date: "6/6/23",
    availability: "In- stock",
  },
  {
    key: 8,
    product: "Coca cola",
    price: "205",
    quantity: "41 Packets",
    thresholdValue: "10 Packets",
    date: "11/11/22",
    availability: "Low stock",
  },
];

export default data;